// lib/constants/table-configs/credit-note.ts

import { ColumnConfig } from "@/types/table";

export const creditNoteConfig: ColumnConfig[] = [
  {
    columnKey: "posting_date",
    label: "Posting Date",
    dataType: "date",
    isVisible: true,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 100,
  },
  {
    columnKey: "credit_note_date",
    label: "Document Date",
    dataType: "date",
    isVisible: true,
    isPinned: false,
    columnOrder: 2,
    columnWidth: 100,
  },
  {
    columnKey: "credit_note_no",
    label: "Credit Note No.",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 3,
    columnWidth: 120,
  },
  {
    columnKey: "status",
    label: "Status",
    dataType: "select",
    isVisible: true,
    isPinned: false,
    columnOrder: 4,
    columnWidth: 120,
    optionSource: "ref_credit_note_status",
  },
  {
    columnKey: "customer_no",
    label: "Customer No.",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 5,
    columnWidth: 100,
  },
  {
    columnKey: "customer_name",
    label: "Customer Name",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 6,
    columnWidth: 180,
  },
  {
    columnKey: "bill_to_customer_no",
    label: "Bill-to Customer No.",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 7,
    columnWidth: 120,
  },
  {
    columnKey: "bill_to_customer_name",
    label: "Bill-to Name",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 8,
    columnWidth: 180,
  },
  {
    columnKey: "reference",
    label: "Reference",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 9,
    columnWidth: 120,
  },
  {
    columnKey: "cust_return_no",
    label: "Cust. Return No.",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 10,
    columnWidth: 120,
  },
  {
    columnKey: "cust_order_no",
    label: "Cust. Order No.",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 11,
    columnWidth: 120,
  },
  {
    columnKey: "salesperson",
    label: "Salesperson",
    dataType: "select",
    isVisible: true,
    isPinned: false,
    columnOrder: 12,
    columnWidth: 150,
    optionSource: "sr_sel_emp_sale_dept",
  },
  {
    columnKey: "currency_id",
    label: "Currency",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 13,
    columnWidth: 90,
  },
  {
    columnKey: "subtotal",
    label: "Net Amount",
    dataType: "number",
    isVisible: true,
    isPinned: false,
    columnOrder: 14,
    columnWidth: 130,
  },
  {
    columnKey: "vat_amount",
    label: "VAT Amount",
    dataType: "number",
    isVisible: false,
    isPinned: false,
    columnOrder: 15,
    columnWidth: 120,
  },
  {
    columnKey: "total_amount",
    label: "Total Amount",
    dataType: "number",
    isVisible: true,
    isPinned: false,
    columnOrder: 16,
    columnWidth: 140,
  },
  {
    columnKey: "due_date",
    label: "Due Date",
    dataType: "date",
    isVisible: false,
    isPinned: false,
    columnOrder: 17,
    columnWidth: 100,
  },
  {
    columnKey: "payment_terms",
    label: "Payment Terms",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 18,
    columnWidth: 130,
  },
  {
    columnKey: "payment_method",
    label: "Payment Method",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 19,
    columnWidth: 130,
  },
  {
    columnKey: "shipment_method",
    label: "Shipment Method",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 20,
    columnWidth: 130,
  },
  {
    columnKey: "shipping_agent",
    label: "Shipping Agent",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 21,
    columnWidth: 130,
  },
  {
    columnKey: "contact",
    label: "Contact Person",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 22,
    columnWidth: 140,
  },
  {
    columnKey: "email",
    label: "Email",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 23,
    columnWidth: 180,
  },
  {
    columnKey: "reason",
    label: "Return Reason",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 24,
    columnWidth: 180,
  },
  {
    columnKey: "created_at",
    label: "Created At",
    dataType: "date",
    isVisible: false,
    isPinned: false,
    columnOrder: 25,
    columnWidth: 130,
  },
];