// lib/constants/table-configs/crm_leads.ts

import { ColumnConfig } from "@/types/table";

export const CRM_LeadConfig: ColumnConfig[] = [
  {
    columnKey: "code",
    label: "Code / Ref",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 120,
  },
  {
    columnKey: "name",
    label: "Name",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 2,
    columnWidth: 180,
  },
  {
    columnKey: "primary_city",
    label: "City",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 3,
    columnWidth: 120,
  },
  {
    columnKey: "county",
    label: "County",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 4,
    columnWidth: 120,
  },
  {
    columnKey: "primaryc_name",
    label: "Primary Contact",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 5,
    columnWidth: 150,
  },
  {
    columnKey: "primaryc_email",
    label: "Contact Email",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 6,
    columnWidth: 180,
  },
  {
    columnKey: "primaryc_phone",
    label: "Contact Phone",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 7,
    columnWidth: 140,
  },
  {
    columnKey: "roles",
    label: "Active Roles",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 8,
    columnWidth: 160,
  },
  {
    columnKey: "currency",
    label: "Currency",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 9,
    columnWidth: 100,
  },
  {
    columnKey: "status",
    label: "Status",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 10,
    columnWidth: 100,
  },
  {
    columnKey: "actions",
    label: "Actions",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 11,
    columnWidth: 120,
  },
];