// lib/constants/table-configs/debit-note.ts

import { ColumnConfig } from "@/types/table";

export const debitNotesConfig: ColumnConfig[] = [
  {
    columnKey: "supplierCreditNoteDate",
    label: "DN Date",
    dataType: "date",
    isVisible: true,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 100,
  },
  {
    columnKey: "debitNoteCode",
    label: "DN No.",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 2,
    columnWidth: 110,
  },
  {
    columnKey: "supplierCreditNoteNo",
    label: "Suppl. CN No.",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 3,
    columnWidth: 130,
  },
  {
    columnKey: "prev_code",
    label: "Prev. Code",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 4,
    columnWidth: 100,
  },
  {
    columnKey: "current_stage",
    label: "Current Stage",
    dataType: "select",
    isVisible: true,
    isPinned: false,
    columnOrder: 5,
    columnWidth: 150,
    optionSource: "stages",
  },
  {
    columnKey: "supplierNo",
    label: "Supplier No.",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 6,
    columnWidth: 110,
  },
  {
    columnKey: "supplierName",
    label: "Supplier Name",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 7,
    columnWidth: 180,
  },
  {
    columnKey: "supplierAddress",
    label: "Address Line 1",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 8,
    columnWidth: 180,
  },
  {
    columnKey: "supplierAddress2",
    label: "Address Line 2",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 9,
    columnWidth: 180,
  },
  {
    columnKey: "supplierCity",
    label: "City",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 10,
    columnWidth: 110,
  },
  {
    columnKey: "supplierCounty",
    label: "County",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 11,
    columnWidth: 100,
  },
  {
    columnKey: "supplierPostCode",
    label: "Postcode",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 12,
    columnWidth: 100,
  },
  {
    columnKey: "country",
    label: "Country Code",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 13,
    columnWidth: 100,
  },
  {
    columnKey: "supplierContactName",
    label: "Contact Person",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 14,
    columnWidth: 150,
  },
  {
    columnKey: "supplierContactTelephone",
    label: "Telephone",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 15,
    columnWidth: 150,
  },
  {
    columnKey: "supplierContactEmail",
    label: "Email",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 16,
    columnWidth: 180,
  },
  {
    columnKey: "purchaser",
    label: "Purchaser",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 17,
    columnWidth: 150,
  },
  {
    columnKey: "posting_grp",
    label: "Posting Group",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 18,
    columnWidth: 110,
  },
  {
    columnKey: "segment",
    label: "Segment",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 19,
    columnWidth: 150,
  },
  {
    columnKey: "currency_code",
    label: "Currency",
    dataType: "select",
    isVisible: true,
    isPinned: false,
    columnOrder: 20,
    columnWidth: 90,
    optionSource: "currencies",
  },
  {
    columnKey: "Amount",
    label: "Amount",
    dataType: "number",
    isVisible: true,
    isPinned: false,
    columnOrder: 21,
    columnWidth: 150,
  },
  {
    columnKey: "tax_amount",
    label: "VAT",
    dataType: "number",
    isVisible: false,
    isPinned: false,
    columnOrder: 22,
    columnWidth: 150,
  },
  {
    columnKey: "Amount (incl VAT)",
    label: "Amount Incl. VAT",
    dataType: "number",
    isVisible: false,
    isPinned: false,
    columnOrder: 23,
    columnWidth: 150,
  },
  {
    columnKey: "receipt_date",
    label: "Receipt Date",
    dataType: "date",
    isVisible: false,
    isPinned: false,
    columnOrder: 24,
    columnWidth: 100,
  },
  {
    columnKey: "dispatchDate",
    label: "Dispatch Date",
    dataType: "date",
    isVisible: false,
    isPinned: false,
    columnOrder: 25,
    columnWidth: 100,
  },
  {
    columnKey: "deliveryDate",
    label: "Delivery Date",
    dataType: "date",
    isVisible: false,
    isPinned: false,
    columnOrder: 26,
    columnWidth: 100,
  },
  {
    columnKey: "shipping_agent_code",
    label: "Shipping Agent",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 27,
    columnWidth: 150,
  },
  {
    columnKey: "shipment_method",
    label: "Shipping Method",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 28,
    columnWidth: 150,
  },
  {
    columnKey: "shipToSupplierLocAddress",
    label: "Shipping Address 1",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 29,
    columnWidth: 180,
  },
  {
    columnKey: "shipToSupplierLocAaddress2",
    label: "Shipping Address 2",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 30,
    columnWidth: 180,
  },
  {
    columnKey: "shipToSupplierLocCity",
    label: "Shipping City",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 31,
    columnWidth: 110,
  },
  {
    columnKey: "shipToSupplierLocCounty",
    label: "Shipping County",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 32,
    columnWidth: 120,
  },
  {
    columnKey: "shipToSupplierLocPostCode",
    label: "Shipping Postcode",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 33,
    columnWidth: 150,
  },
  {
    columnKey: "book_in_contact",
    label: "Book In Contact",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 34,
    columnWidth: 150,
  },
  {
    columnKey: "book_in_tel",
    label: "Book In Tel. No.",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 35,
    columnWidth: 150,
  },
  {
    columnKey: "book_in_email",
    label: "Book In Email",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 36,
    columnWidth: 150,
  },
  {
    columnKey: "warehouse_booking_ref",
    label: "W/H Book Ref.",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 37,
    columnWidth: 150,
  },
  {
    columnKey: "customer_warehouse_ref",
    label: "Cust. W/H Ref.",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 38,
    columnWidth: 150,
  },
  {
    columnKey: "purchaseInvoice",
    label: "Linked Invoice",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 39,
    columnWidth: 120,
  },
  {
    columnKey: "purchaseOrderCode",
    label: "Linked PO",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 40,
    columnWidth: 120,
  },
  {
    columnKey: "actions",
    label: "Actions",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 41,
    columnWidth: 100,
  },
];