// lib/constants/table-configs/Employee.ts

import { ColumnConfig } from "@/types/table";

export const EmployeeConfig: ColumnConfig[] = [
  {
    columnKey: "employee_code",
    label: "Code",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 110,
  },
  {
    columnKey: "display_name",
    label: "Full Name",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 2,
    columnWidth: 200,
  },
  {
    columnKey: "email",
    label: "Email",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 3,
    columnWidth: 200,
  },
  {
    columnKey: "phone",
    label: "Phone / Mobile",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 4,
    columnWidth: 150,
  },
  {
    columnKey: "department_name",
    label: "Department",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 5,
    columnWidth: 160,
  },
  {
    columnKey: "designation_name",
    label: "Designation",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 6,
    columnWidth: 160,
  },
  {
    columnKey: "manager_name",
    label: "Manager",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 7,
    columnWidth: 160,
  },
  {
    columnKey: "status",
    label: "Status",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 8,
    columnWidth: 110,
  },
  {
    columnKey: "actions",
    label: "Actions",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 9,
    columnWidth: 100,
  },
];
