// lib/constants/table-configs/Items.ts

import { ColumnConfig } from "@/types/table";

export const itemColumnsConfig: ColumnConfig[] = [
  {
    columnKey: "item_code",
    label: "Item Code",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 140,
  },
  {
    columnKey: "name",
    label: "Name",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 3,
    columnWidth: 220,
  },
  {
    columnKey: "category_name",
    label: "Category",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 4,
    columnWidth: 160,
  },
  {
    columnKey: "brand_name",
    label: "Brand",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 5,
    columnWidth: 150,
  },
  {
    columnKey: "posting_group_name",
    label: "Posting Group",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 6,
    columnWidth: 160,
  },
  {
    columnKey: "item_type_label",
    label: "Item Type",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 7,
    columnWidth: 150,
  },
  {
    columnKey: "status_label",
    label: "Status",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 8,
    columnWidth: 120,
  },
  {
    columnKey: "actions",
    label: "Actions",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 9,
    columnWidth: 100,
  },
];
