// lib/constants/table-configs/party-ledger-activity.ts

import { ColumnConfig } from "@/types/table";

export const partyLedgerActivityColumnsConfig: ColumnConfig[] = [
  {
    columnKey: "posting_date",
    label: "Date",
    dataType: "date",
    isVisible: true,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 100,
  },
  {
    columnKey: "document_no",
    label: "Document No",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 2,
    columnWidth: 140,
  },
  {
    columnKey: "document_type",
    label: "Type",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 3,
    columnWidth: 120,
  },
  {
    columnKey: "currency_code",
    label: "Curr",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 4,
    columnWidth: 70,
  },
  {
    columnKey: "original_amount_fcy",
    label: "Amount (FCY)",
    dataType: "number",
    isVisible: true,
    isPinned: false,
    columnOrder: 5,
    columnWidth: 130,
  },
  {
    columnKey: "remaining_amount_fcy",
    label: "Remaining (FCY)",
    dataType: "number",
    isVisible: true,
    isPinned: false,
    columnOrder: 6,
    columnWidth: 140,
  },
  {
    columnKey: "original_amount_lcy",
    label: "Amount (LCY)",
    dataType: "number",
    isVisible: true,
    isPinned: false,
    columnOrder: 7,
    columnWidth: 130,
  },
  {
    columnKey: "remaining_amount_lcy",
    label: "Remaining (LCY)",
    dataType: "number",
    isVisible: true,
    isPinned: false,
    columnOrder: 8,
    columnWidth: 140,
  },
  {
    columnKey: "allocations",
    label: "Allocations",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 9,
    columnWidth: 90,
  },
  {
    columnKey: "on_hold",
    label: "On Hold",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 10,
    columnWidth: 90,
  },
  {
    columnKey: "action",
    label: "Action",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 11,
    columnWidth: 100,
  },
];