// lib/constants/table-configs/posted-debit-note.ts

import { ColumnConfig } from "@/types/table";

export const postedDebitNotesConfig: ColumnConfig[] = [
  {
    columnKey: "Debit Note Date",
    label: "supplierCreditNoteDate",
    isVisible: true,
    isPinned: false,
    columnWidth: 120,
    dataType: "date",
    columnOrder: 1,
  },
  {
    columnKey: "Posted Debit Note No.",
    label: "invoice_code",
    isVisible: true,
    isPinned: false,
    columnOrder: 2,
    columnWidth: 150,
    dataType: "text",
  },
  {
    columnKey: "Debit Note No.",
    label: "debitNoteCode",
    isVisible: true,
    isPinned: false,
    columnOrder: 3,
    columnWidth: 120,
    dataType: "text",
  },
  {
    columnKey: "Suppl. CN No.",
    label: "supplierCreditNoteNo",
    isVisible: true,
    isPinned: false,
    columnOrder: 4,
    columnWidth: 100,
    dataType: "text",
  },
  {
    columnKey: "Prev. Code",
    label: "prev_code",
    isVisible: false,
    isPinned: false,
    columnOrder: 5,
    columnWidth: 100,
    dataType: "text",
  },
  {
    columnKey: "Current Stage",
    label: "current_stage",
    isVisible: true,
    isPinned: false,
    columnOrder: 6,
    columnWidth: 150,
    dataType: "select",
  },
  {
    columnKey: "Supplier No.",
    label: "supplierNo",
    isVisible: true,
    isPinned: false,
    columnOrder: 7,
    columnWidth: 100,
    dataType: "text",
  },
  {
    columnKey: "Name",
    label: "supplierName",
    isVisible: true,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 180,
    dataType: "text",
  },
  {
    columnKey: "Address Line 1",
    label: "supplierAddress",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 180,
    dataType: "text",
  },
  {
    columnKey: "Address Line 2",
    label: "supplierAddress2",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 180,
    dataType: "text",
  },
  {
    columnKey: "City",
    label: "supplierCity",
    isVisible: true,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 110,
    dataType: "text",
  },
  {
    columnKey: "County",
    label: "supplierCounty",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 100,
    dataType: "text",
  },
  {
    columnKey: "Postcode",
    label: "supplierPostCode",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 100,
    dataType: "text",
  },
  {
    columnKey: "Country Code",
    label: "country",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 100,
    dataType: "text",
  },
  {
    columnKey: "Contact Person",
    label: "supplierContactName",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 150,
    dataType: "text",
  },
  {
    columnKey: "Telephone",
    label: "supplierContactTelephone",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 150,
    dataType: "text",
  },
  {
    columnKey: "Email",
    label: "supplierContactEmail",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 180,
    dataType: "text",
  },
  {
    columnKey: "Purchaser",
    label: "purchaser",
    isVisible: true,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 150,
    dataType: "text",
  },
  {
    columnKey: "Posting Group",
    label: "posting_grp",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 110,
    dataType: "text",
  },
  {
    columnKey: "Segment",
    label: "segment",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 150,
    dataType: "text",
  },
  {
    columnKey: "Currency",
    label: "currency_code",
    isVisible: true,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 90,
    dataType: "text",
  },
  {
    columnKey: "Amount",
    label: "Amount",
    isVisible: true,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 150,
    dataType: "number",
  },
  {
    columnKey: "VAT",
    label: "tax_amount",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 150,
    dataType: "number",
  },
  {
    columnKey: "Amount Incl VAT",
    label: "Amount (incl VAT)",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 150,
    dataType: "number",
  },
  {
    columnKey: "Req. Rcpt. Date",
    label: "receipt_date",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 100,
    dataType: "date",
  },
  {
    columnKey: "Dispatch Date",
    label: "dispatchDate",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 100,
    dataType: "date",
  },
  {
    columnKey: "Delivery Date",
    label: "deliveryDate",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 100,
    dataType: "date",
  },
  {
    columnKey: "Shipping Agent",
    label: "shipping_agent_code",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 150,
    dataType: "text",
  },
  {
    columnKey: "Shipping Method",
    label: "shipment_method",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 150,
    dataType: "text",
  },
  {
    columnKey: "Shipping Address 1",
    label: "shipToSupplierLocAddress",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 180,
    dataType: "text",
  },
  {
    columnKey: "Shipping Address 2 ",
    label: "shipToSupplierLocAaddress2",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 180,
    dataType: "text",
  },
  {
    columnKey: "Shipping City",
    label: "shipToSupplierLocCity",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 110,
    dataType: "text",
  },
  {
    columnKey: "Shipping County",
    label: "shipToSupplierLocCounty",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 110,
    dataType: "text",
  },
  {
    columnKey: "Shipping Postcode",
    label: "shipToSupplierLocPostCode",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 110,
    dataType: "text",
  },
  {
    columnKey: "Book In Contact",
    label: "book_in_contact",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 150,
    dataType: "text",
  },
  {
    columnKey: "Book In Tel No.",
    label: "book_in_tel",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 150,
    dataType: "text",
  },
  {
    columnKey: "Book In Email",
    label: "book_in_email",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 180,
    dataType: "text",
  },
  {
    columnKey: "Supplier Ref. No.",
    label: "supplierReferenceNo",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 150,
    dataType: "text",
  },
  {
    columnKey: "Shipping Agent's Ref No.",
    label: "shippingAgentRefNo",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 160,
    dataType: "text",
  },
  {
    columnKey: "W/H Book Ref.",
    label: "warehouse_booking_ref",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 150,
    dataType: "text",
  },
  {
    columnKey: "Suppl W/H Ref No.",
    label: "customer_warehouse_ref",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 150,
    dataType: "text",
  },
  {
    columnKey: "Linked PI",
    label: "purchaseInvoice",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 100,
    dataType: "text",
  },
  {
    columnKey: "Linked PO",
    label: "purchaseOrderCode",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 100,
    dataType: "text",
  },
  {
    columnKey: "VAT Posted",
    label: "vatPosted",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 110,
    dataType: "text",
  },
  {
    columnKey: "Docs. Attached for DN",
    label: "documentDNCount",
    isVisible: true,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 110,
    dataType: "number",
  },
  {
    columnKey: "Docs. Attached for PDN",
    label: "documentPDNCount",
    isVisible: true,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 110,
    dataType: "number",
  },
  {
    columnKey: "Emails Sent",
    label: "emailCount",
    isVisible: true,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 90,
    dataType: "number",
  },
];
