// lib/constants/table-configs/posted-debit-note.ts

import { ColumnConfig } from "@/types/table";

export const postedDebitNotesConfig: ColumnConfig[] = [
  {
    columnKey: "supplierCreditNoteDate",
    label: "Debit Note Date",
    isVisible: true,
    isPinned: false,
    columnWidth: 120,
    dataType: "date",
    columnOrder: 1,
  },
  {
    columnKey: "invoice_code",
    label: "Posted Debit Note No.",
    isVisible: true,
    isPinned: false,
    columnOrder: 2,
    columnWidth: 150,
    dataType: "text",
  },
  {
    columnKey: "debitNoteCode",
    label: "Debit Note No.",
    isVisible: true,
    isPinned: false,
    columnOrder: 3,
    columnWidth: 120,
    dataType: "text",
  },
  {
    columnKey: "supplierCreditNoteNo",
    label: "Suppl. CN No.",
    isVisible: true,
    isPinned: false,
    columnOrder: 4,
    columnWidth: 100,
    dataType: "text",
  },
  {
    columnKey: "Prev. Code",
    label: "prev_code",
    isVisible: false,
    isPinned: false,
    columnOrder: 5,
    columnWidth: 100,
    dataType: "text",
  },
  {
    columnKey: "Current Stage",
    label: "current_stage",
    isVisible: true,
    isPinned: false,
    columnOrder: 6,
    columnWidth: 150,
    dataType: "select",
  },
  {
    columnKey: "supplierNo",
    label: "Supplier No.",
    isVisible: true,
    isPinned: false,
    columnOrder: 7,
    columnWidth: 100,
    dataType: "text",
  },
  {
    columnKey: "supplierName",
    label: "Name",
    isVisible: true,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 180,
    dataType: "text",
  },
  {
    columnKey: "supplierAddress",
    label: "Address Line 1",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 180,
    dataType: "text",
  },
  {
    columnKey: "supplierAddress2",
    label: "Address Line 2",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 180,
    dataType: "text",
  },
  {
    columnKey: "supplierCity",
    label: "City",
    isVisible: true,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 110,
    dataType: "text",
  },
  {
    columnKey: "supplierCounty",
    label: "County",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 100,
    dataType: "text",
  },
  {
    columnKey: "supplierPostCode",
    label: "Postcode",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 100,
    dataType: "text",
  },
  {
    columnKey: "country",
    label: "Country Code",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 100,
    dataType: "text",
  },
  {
    columnKey: "supplierContactName",
    label: "Contact Person",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 150,
    dataType: "text",
  },
  {
    columnKey: "supplierContactTelephone",
    label: "Telephone",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 150,
    dataType: "text",
  },
  {
    columnKey: "supplierContactEmail",
    label: "Email",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 180,
    dataType: "text",
  },
  {
    label: "Purchaser",
    columnKey: "purchaser",
    isVisible: true,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 150,
    dataType: "text",
  },
  {
    label: "Posting Group",
    columnKey: "posting_grp",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 110,
    dataType: "text",
  },
  {
    label: "Segment",
    columnKey: "segment",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 150,
    dataType: "text",
  },
  {
    label: "Currency",
    columnKey: "currency_code",
    isVisible: true,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 90,
    dataType: "text",
  },
  {
    columnKey: "Amount",
    label: "Amount",
    isVisible: true,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 150,
    dataType: "number",
  },
  {
    label: "VAT",
    columnKey: "tax_amount",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 150,
    dataType: "number",
  },
  {
    label: "Amount Incl VAT",
    columnKey: "Amount (incl VAT)",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 150,
    dataType: "number",
  },
  {
    label: "Req. Rcpt. Date",
    columnKey: "receipt_date",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 100,
    dataType: "date",
  },
  {
    label: "Dispatch Date",
    columnKey: "dispatchDate",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 100,
    dataType: "date",
  },
  {
    label: "Delivery Date",
    columnKey: "deliveryDate",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 100,
    dataType: "date",
  },
  {
    label: "Shipping Agent",
    columnKey: "shipping_agent_code",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 150,
    dataType: "text",
  },
  {
    label: "Shipping Method",
    columnKey: "shipment_method",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 150,
    dataType: "text",
  },
  {
    label: "Shipping Address 1",
    columnKey: "shipToSupplierLocAddress",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 180,
    dataType: "text",
  },
  {
    label: "Shipping Address 2 ",
    columnKey: "shipToSupplierLocAaddress2",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 180,
    dataType: "text",
  },
  {
    label: "Shipping City",
    columnKey: "shipToSupplierLocCity",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 110,
    dataType: "text",
  },
  {
    label: "Shipping County",
    columnKey: "shipToSupplierLocCounty",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 110,
    dataType: "text",
  },
  {
    label: "Shipping Postcode",
    columnKey: "shipToSupplierLocPostCode",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 110,
    dataType: "text",
  },
  {
    label: "Book In Contact",
    columnKey: "book_in_contact",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 150,
    dataType: "text",
  },
  {
    label: "Book In Tel No.",
    columnKey: "book_in_tel",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 150,
    dataType: "text",
  },
  {
    label: "Book In Email",
    columnKey: "book_in_email",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 180,
    dataType: "text",
  },
  {
    label: "Supplier Ref. No.",
    columnKey: "supplierReferenceNo",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 150,
    dataType: "text",
  },
  {
    label: "Shipping Agent's Ref No.",
    columnKey: "shippingAgentRefNo",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 160,
    dataType: "text",
  },
  {
    label: "W/H Book Ref.",
    columnKey: "warehouse_booking_ref",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 150,
    dataType: "text",
  },
  {
    label: "Suppl W/H Ref No.",
    columnKey: "customer_warehouse_ref",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 150,
    dataType: "text",
  },
  {
    label: "Linked PI",
    columnKey: "purchaseInvoice",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 100,
    dataType: "text",
  },
  {
    label: "Linked PO",
    columnKey: "purchaseOrderCode",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 100,
    dataType: "text",
  },
  {
    label: "VAT Posted",
    columnKey: "vatPosted",
    isVisible: false,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 110,
    dataType: "text",
  },
  {
    label: "Docs. Attached for DN",
    columnKey: "documentDNCount",
    isVisible: true,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 110,
    dataType: "number",
  },
  {
    label: "Docs. Attached for PDN",
    columnKey: "documentPDNCount",
    isVisible: true,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 110,
    dataType: "number",
  },
  {
    label: "Emails Sent",
    columnKey: "emailCount",
    isVisible: true,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 90,
    dataType: "number",
  },
];
