// lib/constants/table-configs/posted-ledger-entries.ts

import { ColumnConfig } from "@/types/table";

export const postedLedgerEntriesConfig: ColumnConfig[] = [
  {
    columnKey: "posting_date",
    label: "Posting Date",
    isVisible: true,
    columnWidth: 110,
    columnOrder: 1,
    isPinned: false,
    dataType: "date",
  },
  {
    columnKey: "document_type",
    label: "Doc Type",
    isVisible: true,
    columnWidth: 120,
    columnOrder: 2,
    isPinned: false,
    dataType: "text",
  },
  {
    columnKey: "document_number",
    label: "Doc No.",
    isVisible: true,
    columnWidth: 140,
    columnOrder: 3,
    isPinned: false,
    dataType: "text",
  },
  {
    columnKey: "gl_no",
    label: "G/L Account No.",
    isVisible: true,
    columnWidth: 130,
    columnOrder: 4,
    isPinned: false,
    dataType: "text",
  },
  {
    columnKey: "name",
    label: "G/L Account Name",
    isVisible: true,
    columnWidth: 220,
    columnOrder: 5,
    isPinned: false,
    dataType: "text",
  },
  {
    columnKey: "source_no",
    label: "Source No.",
    isVisible: true,
    columnWidth: 120,
    columnOrder: 6,
    isPinned: false,
    dataType: "text",
  },
  {
    columnKey: "currency_code",
    label: "Curr.",
    isVisible: true,
    columnWidth: 80,
    columnOrder: 7,
    isPinned: false,
    dataType: "text",
  },
  {
    columnKey: "currency_factor",
    label: "Exch. Rate",
    isVisible: false, // Hidden by default, enableable via column picker
    columnWidth: 100,
    columnOrder: 8,
    isPinned: false,
    dataType: "text",
  },

  // Foreign Currency (FCY) Fields
  {
    columnKey: "debit",
    label: "Debit (FCY)",
    isVisible: true,
    columnWidth: 130,
    columnOrder: 9,
    isPinned: false,
    dataType: "text",
  },
  {
    columnKey: "credit",
    label: "Credit (FCY)",
    isVisible: true,
    columnWidth: 130,
    columnOrder: 10,
    isPinned: false,
    dataType: "text",
  },
  {
    columnKey: "amount",
    label: "Amount (FCY)",
    isVisible: false,
    columnWidth: 130,
    columnOrder: 11,
    isPinned: false,
    dataType: "text",
  },

  // Local Currency (LCY) Fields
  {
    columnKey: "debit_lcy",
    label: "Debit (LCY)",
    isVisible: true,
    columnWidth: 130,
    columnOrder: 12,
    isPinned: false,
    dataType: "text",
  },
  {
    columnKey: "credit_lcy",
    label: "Credit (LCY)",
    isVisible: true,
    columnWidth: 130,
    columnOrder: 13,
    isPinned: false,
    dataType: "text",
  },
  {
    columnKey: "amount_lcy",
    label: "Amount (LCY)",
    isVisible: true,
    columnWidth: 130,
    columnOrder: 14,
    isPinned: false,
    dataType: "text",
  },

  // Audit Fields
  {
    columnKey: "user_id",
    label: "User ID",
    isVisible: true,
    columnWidth: 110,
    columnOrder: 15,
    isPinned: false,
    dataType: "text",
  },
  {
    columnKey: "entry_no",
    label: "Entry No.",
    isVisible: true,
    columnWidth: 100,
    columnOrder: 16,
    isPinned: false,
    dataType: "text",
  },
];
