// lib/constants/table-configs/posted-credit-note.ts

import { ColumnConfig } from "@/types/table";

export const postedCreditNoteConfig: ColumnConfig[] = [
  {
    columnKey: "posted_at",
    label: "Posted Date",
    dataType: "date",
    isVisible: true,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 100,
  },
  {
    columnKey: "posted_credit_note_no",
    label: "Posted Doc. No.",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 2,
    columnWidth: 130,
  },
  {
    columnKey: "credit_note_no",
    label: "Pre-Post No.",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 3,
    columnWidth: 120,
  },
  {
    columnKey: "customer_no",
    label: "Customer No.",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 4,
    columnWidth: 100,
  },
  {
    columnKey: "customer_name",
    label: "Customer Name",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 5,
    columnWidth: 180,
  },
  {
    columnKey: "bill_to_customer_no",
    label: "Bill-to Customer No.",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 6,
    columnWidth: 120,
  },
  {
    columnKey: "bill_to_customer_name",
    label: "Bill-to Name",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 7,
    columnWidth: 180,
  },
  {
    columnKey: "reference",
    label: "Reference",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 8,
    columnWidth: 120,
  },
  {
    columnKey: "cust_return_no",
    label: "Cust. Return No.",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 9,
    columnWidth: 120,
  },
  {
    columnKey: "salesperson",
    label: "Salesperson",
    dataType: "select",
    isVisible: true,
    isPinned: false,
    columnOrder: 10,
    columnWidth: 150,
    optionSource: "sr_sel_emp_sale_dept",
  },
  {
    columnKey: "currency_id",
    label: "Currency",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 11,
    columnWidth: 90,
  },
  {
    columnKey: "subtotal",
    label: "Net Amount",
    dataType: "number",
    isVisible: true,
    isPinned: false,
    columnOrder: 12,
    columnWidth: 130,
  },
  {
    columnKey: "vat_amount",
    label: "VAT Amount",
    dataType: "number",
    isVisible: false,
    isPinned: false,
    columnOrder: 13,
    columnWidth: 120,
  },
  {
    columnKey: "total_amount",
    label: "Total Amount",
    dataType: "number",
    isVisible: true,
    isPinned: false,
    columnOrder: 14,
    columnWidth: 140,
  },
  {
    columnKey: "credited_amount",
    label: "Credited Amount",
    dataType: "number",
    isVisible: true,
    isPinned: false,
    columnOrder: 15,
    columnWidth: 130,
  },
  {
    columnKey: "due_date",
    label: "Due Date",
    dataType: "date",
    isVisible: false,
    isPinned: false,
    columnOrder: 16,
    columnWidth: 100,
  },
  {
    columnKey: "credit_status",
    label: "Credit Status",
    dataType: "select",
    isVisible: true,
    isPinned: false,
    columnOrder: 17,
    columnWidth: 120,
    optionSource: "ref_credit_status",
  },
  {
    columnKey: "payment_terms",
    label: "Payment Terms",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 18,
    columnWidth: 130,
  },
  {
    columnKey: "receivable_bank",
    label: "Receivable Bank",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 19,
    columnWidth: 150,
  },
  {
    columnKey: "reason",
    label: "Reason",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 20,
    columnWidth: 180,
  },
];