// lib/constants/table-configs/purchase-orders.ts

import { ColumnConfig } from "@/types/table";

export const purchaseOrdersConfig: ColumnConfig[] = [
  {
    columnKey: "invoice_date",
    label: "Invoice Date",
    dataType: "date",
    isVisible: true,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 100,
  },
  {
    columnKey: "order_date",
    label: "Order Date",
    dataType: "date",
    isVisible: true,
    isPinned: false,
    columnOrder: 2,
    columnWidth: 100,
  },
  {
    columnKey: "order_no",
    label: "Order No.",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 3,
    columnWidth: 100,
  },
  {
    columnKey: "supp_order_no",
    label: "Suppl. Invoice No.",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 4,
    columnWidth: 130,
  },
  {
    columnKey: "previous_code",
    label: "Prev. Code",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 5,
    columnWidth: 100,
  },
  {
    columnKey: "current_stage",
    label: "Current Stage",
    dataType: "select",
    isVisible: true,
    isPinned: false,
    columnOrder: 6,
    columnWidth: 150,
    optionSource: "stages",
  },
  {
    columnKey: "supplier_no",
    label: "Supplier No.",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 7,
    columnWidth: 100,
  },
  {
    columnKey: "supplier_name",
    label: "Name",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 8,
    columnWidth: 180,
  },
  {
    columnKey: "supplier_address",
    label: "Address Line 1",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 9,
    columnWidth: 180,
  },
  {
    columnKey: "supplier_address2",
    label: "Address Line 2",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 10,
    columnWidth: 180,
  },
  {
    columnKey: "city",
    label: "City",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 11,
    columnWidth: 110,
  },
  {
    columnKey: "county",
    label: "County",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 12,
    columnWidth: 100,
  },
  {
    columnKey: "post_code",
    label: "Postcode",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 13,
    columnWidth: 100,
  },
  {
    columnKey: "country",
    label: "Country Code",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 14,
    columnWidth: 100,
  },
  {
    columnKey: "contact",
    label: "Contact Person",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 15,
    columnWidth: 150,
  },
  {
    columnKey: "phone",
    label: "Telephone",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 16,
    columnWidth: 150,
  },
  {
    columnKey: "email",
    label: "Email",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 17,
    columnWidth: 180,
  },
  {
    columnKey: "purchaser",
    label: "Purchaser",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 18,
    columnWidth: 150,
  },
  {
    columnKey: "posting_group",
    label: "Posting Group",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 19,
    columnWidth: 110,
  },
  {
    columnKey: "segment",
    label: "Segment",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 20,
    columnWidth: 150,
  },
  {
    columnKey: "currency",
    label: "Currency",
    dataType: "select",
    isVisible: true,
    isPinned: false,
    columnOrder: 21,
    columnWidth: 90,
    optionSource: "currencies",
  },
  {
    columnKey: "net_amount",
    label: "Amount",
    dataType: "number",
    isVisible: true,
    isPinned: false,
    columnOrder: 22,
    columnWidth: 150,
  },
  {
    columnKey: "vat_amount",
    label: "VAT",
    dataType: "number",
    isVisible: false,
    isPinned: false,
    columnOrder: 23,
    columnWidth: 150,
  },
  {
    columnKey: "total_amount",
    label: "Amount Incl. VAT",
    dataType: "number",
    isVisible: false,
    isPinned: false,
    columnOrder: 24,
    columnWidth: 150,
  },
  {
    columnKey: "due_date",
    label: "Due Date",
    dataType: "date",
    isVisible: false,
    isPinned: false,
    columnOrder: 25,
    columnWidth: 100,
  },
  {
    columnKey: "req_receipt_date",
    label: "Req. Rcpt. Date",
    dataType: "date",
    isVisible: true,
    isPinned: false,
    columnOrder: 26,
    columnWidth: 110,
  },
  {
    columnKey: "receipt_date",
    label: "Receipt Date",
    dataType: "date",
    isVisible: false,
    isPinned: false,
    columnOrder: 27,
    columnWidth: 100,
  },
  {
    columnKey: "shipping_agent",
    label: "Shipping Agent",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 28,
    columnWidth: 150,
  },
  {
    columnKey: "shipment_method",
    label: "Shipping Method",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 29,
    columnWidth: 150,
  },
  {
    columnKey: "ship_to_address",
    label: "Shipping Address 1",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 30,
    columnWidth: 180,
  },
  {
    columnKey: "ship_to_address2",
    label: "Shipping Address 2",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 31,
    columnWidth: 180,
  },
  {
    columnKey: "ship_to_city",
    label: "Shipping City",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 32,
    columnWidth: 110,
  },
  {
    columnKey: "ship_to_county",
    label: "Shipping County",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 33,
    columnWidth: 120,
  },
  {
    columnKey: "ship_to_post_code",
    label: "Shipping Postcode",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 34,
    columnWidth: 150,
  },
  {
    columnKey: "book_in_contact",
    label: "Book In Contact",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 35,
    columnWidth: 150,
  },
  {
    columnKey: "book_in_phone",
    label: "Book In Tel. No.",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 36,
    columnWidth: 150,
  },
  {
    columnKey: "book_in_email",
    label: "Book In Email",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 37,
    columnWidth: 150,
  },
  {
    columnKey: "warehouse_ref_no",
    label: "W/H Book Ref.",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 38,
    columnWidth: 150,
  },
  {
    columnKey: "consignment_no",
    label: "Cons. No.",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 39,
    columnWidth: 150,
  },
  {
    columnKey: "link_to_so_no",
    label: "Linked SO",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 40,
    columnWidth: 100,
  },
  {
    columnKey: "cust_order_no",
    label: "Suppl. Order No.",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 41,
    columnWidth: 130,
  },
  {
    columnKey: "actions",
    label: "Actions",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 42,
    columnWidth: 100,
  },
];
