// lib/constants/table-configs/purchase-orders.ts

import { ColumnConfig } from "@/types/table";

export const purchaseOrdersConfig: ColumnConfig[] = [
  {
    columnKey: "invoice_date",
    label: "Invoice Date",
    dataType: "date",
    isVisible: true,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 140,
  },
  {
    columnKey: "order_date",
    label: "Order Date",
    dataType: "date",
    isVisible: true,
    isPinned: false,
    columnOrder: 2,
    columnWidth: 140,
  },
  {
    columnKey: "order_no",
    label: "Order No.",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 3,
    columnWidth: 130,
  },
  {
    columnKey: "supplier_invoice_no",
    label: "Suppl. Invoice No.",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 4,
    columnWidth: 150,
  },
  {
    columnKey: "current_stage",
    label: "Current Stage",
    dataType: "select",
    isVisible: true,
    isPinned: false,
    columnOrder: 5,
    columnWidth: 140,
    optionSource: "stages",
    // options: [
    //   { label: "PO Sent", value: "PO Sent" },
    //   { label: "Completed", value: "Completed" },
    //   { label: "Draft", value: "Draft" },
    // ],
  },
  {
    columnKey: "supplier_no",
    label: "Supplier No.",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 6,
    columnWidth: 120,
  },
  {
    columnKey: "supplier_name",
    label: "Name",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 7,
    columnWidth: 220,
  },
  {
    columnKey: "city",
    label: "City",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 8,
    columnWidth: 130,
  },
  {
    columnKey: "contact_person",
    label: "Contact Person",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 9,
    columnWidth: 150,
  },
  {
    columnKey: "purchaser",
    label: "Purchaser",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 10,
    columnWidth: 140,
  },
  {
    columnKey: "currency",
    label: "Currency",
    dataType: "select",
    isVisible: true,
    isPinned: false,
    columnOrder: 11,
    columnWidth: 100,
    optionSource: "currencies",
    // options: [
    //   { label: "EUR", value: "EUR" },
    //   { label: "GBP", value: "GBP" },
    //   { label: "USD", value: "USD" },
    // ],
  },
  {
    columnKey: "total_amount",
    label: "Amount",
    dataType: "number",
    isVisible: true,
    isPinned: false,
    columnOrder: 12,
    columnWidth: 130,
  },
  {
    columnKey: "actions",
    label: "Actions",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 13,
    columnWidth: 100,
  },
];
