// lib/constants/table-configs/sales-invoices.ts

import { ColumnConfig } from "@/types/table";

export const salesInvoicesConfig: ColumnConfig[] = [
  {
    columnKey: "invoice_date",
    label: "Invoice Date",
    dataType: "date",
    isVisible: true,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 100,
  },
  {
    columnKey: "invoice_no",
    label: "Invoice No.",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 2,
    columnWidth: 110,
  },
  {
    columnKey: "status",
    label: "Status",
    dataType: "select",
    isVisible: true,
    isPinned: false,
    columnOrder: 3,
    columnWidth: 120,
    optionSource: "ref_invoice_statuses",
  },
  {
    columnKey: "is_posted",
    label: "Posted",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 4,
    columnWidth: 90,
  },
  {
    columnKey: "customer_no",
    label: "Customer No.",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 5,
    columnWidth: 100,
  },
  {
    columnKey: "customer_name",
    label: "Customer Name",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 6,
    columnWidth: 180,
  },
  {
    columnKey: "reference",
    label: "Reference",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 7,
    columnWidth: 130,
  },
  {
    columnKey: "currency_code",
    label: "Currency",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 8,
    columnWidth: 90,
  },
  {
    columnKey: "exchange_rate",
    label: "Exchange Rate",
    dataType: "number",
    isVisible: false,
    isPinned: false,
    columnOrder: 9,
    columnWidth: 110,
  },
  {
    columnKey: "subtotal",
    label: "Net Amount",
    dataType: "number",
    isVisible: true,
    isPinned: false,
    columnOrder: 10,
    columnWidth: 130,
  },
  {
    columnKey: "vat_amount",
    label: "VAT",
    dataType: "number",
    isVisible: true,
    isPinned: false,
    columnOrder: 11,
    columnWidth: 120,
  },
  {
    columnKey: "discount_amount",
    label: "Discount",
    dataType: "number",
    isVisible: false,
    isPinned: false,
    columnOrder: 12,
    columnWidth: 110,
  },
  {
    columnKey: "total_amount",
    label: "Total Amount",
    dataType: "number",
    isVisible: true,
    isPinned: false,
    columnOrder: 13,
    columnWidth: 140,
  },
  {
    columnKey: "due_date",
    label: "Due Date",
    dataType: "date",
    isVisible: true,
    isPinned: false,
    columnOrder: 14,
    columnWidth: 100,
  },
  {
    columnKey: "posted_at",
    label: "Posted At",
    dataType: "date",
    isVisible: false,
    isPinned: false,
    columnOrder: 15,
    columnWidth: 130,
  },
  {
    columnKey: "remarks",
    label: "Remarks",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 16,
    columnWidth: 180,
  },
  {
    columnKey: "created_at",
    label: "Created At",
    dataType: "date",
    isVisible: false,
    isPinned: false,
    columnOrder: 17,
    columnWidth: 130,
  },
];