// lib/constants/table-configs/sales-orders.ts

import { ColumnConfig } from "@/types/table";

export const salesOrdersConfig: ColumnConfig[] = [
  {
    columnKey: "posting_date",
    label: "Invoice Date",
    dataType: "date",
    isVisible: true,
    isPinned: false,
    columnOrder: 1,
    columnWidth: 100,
  },
  {
    columnKey: "offer_date",
    label: "Order Date",
    dataType: "date",
    isVisible: true,
    isPinned: false,
    columnOrder: 2,
    columnWidth: 100,
  },
  {
    columnKey: "sale_order_code",
    label: "Order No.",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 3,
    columnWidth: 100,
  },
  {
    columnKey: "sale_quote_code",
    label: "Quote No.",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 4,
    columnWidth: 100,
  },
  {
    columnKey: "cust_order_no",
    label: "Cust. Order No.",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 5,
    columnWidth: 110,
  },
  {
    columnKey: "prev_code",
    label: "Prev. Code",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 6,
    columnWidth: 100,
  },
  {
    columnKey: "current_stage",
    label: "Current Stage",
    dataType: "select",
    isVisible: true,
    isPinned: false,
    columnOrder: 7,
    columnWidth: 150,
    optionSource: "ref_crm_order_stages",
  },
  {
    columnKey: "sell_to_cust_no",
    label: "Customer No.",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 8,
    columnWidth: 100,
  },
  {
    columnKey: "sell_to_cust_name",
    label: "Name",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 9,
    columnWidth: 180,
  },
  {
    columnKey: "sell_to_address",
    label: "Address Line 1",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 10,
    columnWidth: 180,
  },
  {
    columnKey: "sell_to_address2",
    label: "Address Line 2",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 11,
    columnWidth: 180,
  },
  {
    columnKey: "sell_to_city",
    label: "City",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 12,
    columnWidth: 110,
  },
  {
    columnKey: "sell_to_county",
    label: "County",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 13,
    columnWidth: 100,
  },
  {
    columnKey: "sell_to_post_code",
    label: "Postcode",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 14,
    columnWidth: 100,
  },
  {
    columnKey: "country_code",
    label: "Country Code",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 15,
    columnWidth: 100,
  },
  {
    columnKey: "sell_to_contact_no",
    label: "Contact Person",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 16,
    columnWidth: 150,
  },
  {
    columnKey: "cust_phone",
    label: "Telephone",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 17,
    columnWidth: 150,
  },
  {
    columnKey: "cust_email",
    label: "Email",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 18,
    columnWidth: 180,
  },
  {
    columnKey: "sale_person",
    label: "Salesperson",
    dataType: "select",
    isVisible: true,
    isPinned: false,
    columnOrder: 19,
    columnWidth: 150,
    optionSource: "sr_sel_emp_sale_dept",
  },
  {
    columnKey: "bill_to_posting_group_name",
    label: "Posting Group",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 20,
    columnWidth: 110,
  },
  {
    columnKey: "segment",
    label: "Segment",
    dataType: "select",
    isVisible: false,
    isPinned: false,
    columnOrder: 21,
    columnWidth: 150,
    optionSource: "crm_segment",
  },
  {
    columnKey: "currency_code",
    label: "Currency",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 22,
    columnWidth: 90,
  },
  {
    columnKey: "net_amount",
    label: "Amount",
    dataType: "number",
    isVisible: true,
    isPinned: false,
    columnOrder: 23,
    columnWidth: 150,
  },
  {
    columnKey: "tax_amount",
    label: "VAT",
    dataType: "number",
    isVisible: false,
    isPinned: false,
    columnOrder: 24,
    columnWidth: 150,
  },
  {
    columnKey: "grand_total",
    label: "Amount Incl. VAT",
    dataType: "number",
    isVisible: false,
    isPinned: false,
    columnOrder: 25,
    columnWidth: 150,
  },
  {
    columnKey: "due_date",
    label: "Due Date",
    dataType: "date",
    isVisible: false,
    isPinned: false,
    columnOrder: 26,
    columnWidth: 100,
  },
  {
    columnKey: "finance_charges_exists",
    label: "Finance Charges",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 27,
    columnWidth: 100,
  },
  {
    columnKey: "insurance_charges_exists",
    label: "Insurance Charges",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 28,
    columnWidth: 100,
  },
  {
    columnKey: "requested_delivery_date",
    label: "Req. Del. Date",
    dataType: "date",
    isVisible: true,
    isPinned: false,
    columnOrder: 29,
    columnWidth: 110,
  },
  {
    columnKey: "dispatch_date",
    label: "Dispatch Date",
    dataType: "date",
    isVisible: false,
    isPinned: false,
    columnOrder: 30,
    columnWidth: 100,
  },
  {
    columnKey: "delivery_date",
    label: "Delivery Date",
    dataType: "date",
    isVisible: false,
    isPinned: false,
    columnOrder: 31,
    columnWidth: 100,
  },
  {
    columnKey: "proof_of_delivery",
    label: "Proof of Del.",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 32,
    columnWidth: 80,
  },
  {
    columnKey: "shipping_agent_code",
    label: "Shipping Agent",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 33,
    columnWidth: 150,
  },
  {
    columnKey: "shipment_method_code",
    label: "Shipping Method",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 34,
    columnWidth: 150,
  },
  {
    columnKey: "ship_to_address",
    label: "Shipping Address 1",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 35,
    columnWidth: 180,
  },
  {
    columnKey: "ship_to_address2",
    label: "Shipping Address 2",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 36,
    columnWidth: 180,
  },
  {
    columnKey: "ship_to_city",
    label: "Shipping City",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 37,
    columnWidth: 110,
  },
  {
    columnKey: "ship_to_county",
    label: "Shipping County",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 38,
    columnWidth: 120,
  },
  {
    columnKey: "ship_to_post_code",
    label: "Shipping Postcode",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 39,
    columnWidth: 120,
  },
  {
    columnKey: "book_in_tel",
    label: "Book In Contact",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 40,
    columnWidth: 150,
  },
  {
    columnKey: "comm_book_in_contact",
    label: "Book In Tel. No.",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 41,
    columnWidth: 150,
  },
  {
    columnKey: "book_in_email",
    label: "Book In Email",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 42,
    columnWidth: 180,
  },
  {
    columnKey: "warehouse_booking_ref",
    label: "W/H Book. Ref.",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 43,
    columnWidth: 150,
  },
  {
    columnKey: "customer_warehouse_ref",
    label: "Cust. W/H Ref.",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 44,
    columnWidth: 150,
  },
  {
    columnKey: "linked_pos_1",
    label: "Linked PO",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 45,
    columnWidth: 100,
  },
  {
    columnKey: "converted_to_so_on",
    label: "Conv. to SO On",
    dataType: "date",
    isVisible: false,
    isPinned: false,
    columnOrder: 46,
    columnWidth: 100,
  },
  {
    columnKey: "converted_to_so_by_name",
    label: "Conv. to SO By",
    dataType: "text",
    isVisible: false,
    isPinned: false,
    columnOrder: 47,
    columnWidth: 100,
  },
  {
    columnKey: "documentSQCount",
    label: "Docs. Attached for SQ",
    dataType: "number",
    isVisible: true,
    isPinned: false,
    columnOrder: 48,
    columnWidth: 110,
  },
  {
    columnKey: "documentSOCount",
    label: "Docs. Attached for SO",
    dataType: "number",
    isVisible: true,
    isPinned: false,
    columnOrder: 49,
    columnWidth: 110,
  },
  {
    columnKey: "emailCount",
    label: "Emails Sent",
    dataType: "number",
    isVisible: true,
    isPinned: false,
    columnOrder: 50,
    columnWidth: 110,
  },
  {
    columnKey: "ma_approval_status",
    label: "Margin Analysis Approval Status",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 51,
    columnWidth: 210,
  },
  {
    columnKey: "cl_approval_status",
    label: "Credit Limit Approval Status",
    dataType: "text",
    isVisible: true,
    isPinned: false,
    columnOrder: 52,
    columnWidth: 210,
  },
];